//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfs.Restful {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class VfsHttpHeaders : global::System.Configuration.ApplicationSettingsBase {
        
        private static VfsHttpHeaders defaultInstance = ((VfsHttpHeaders)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new VfsHttpHeaders())));
        
        public static VfsHttpHeaders Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vfs-block-length")]
        public string BlockLength {
            get {
                return ((string)(this["BlockLength"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vfs-block-number")]
        public string BlockNumber {
            get {
                return ((string)(this["BlockNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vfs-block-islast")]
        public string IsLastBlock {
            get {
                return ((string)(this["IsLastBlock"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vfs-block-offset")]
        public string BlockOffset {
            get {
                return ((string)(this["BlockOffset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vfs-transfer-id")]
        public string TransferId {
            get {
                return ((string)(this["TransferId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vfs-overwrite")]
        public string OverwriteExistingResource {
            get {
                return ((string)(this["OverwriteExistingResource"]));
            }
        }
    }
}
