//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vfs.Restful {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class VfsUris : global::System.Configuration.ApplicationSettingsBase {
        
        private static VfsUris defaultInstance = ((VfsUris)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new VfsUris())));
        
        public static VfsUris Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string GetFileSystemRootUri {
            get {
                return ((string)(this["GetFileSystemRootUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files?path={filepath}")]
        public string GetFileInfoUri {
            get {
                return ((string)(this["GetFileInfoUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("folders?path={folderpath}")]
        public string GetFolderInfoUri {
            get {
                return ((string)(this["GetFolderInfoUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("folders/files?parentfolder={parentfolderpath}")]
        public string GetChildFilesUri {
            get {
                return ((string)(this["GetChildFilesUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("folders/subfolders?parentfolder={parentfolderpath}")]
        public string GetChildFoldersUri {
            get {
                return ((string)(this["GetChildFoldersUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("folders/contents?parentfolder={parentfolderpath}")]
        public string GetFolderContentsUri {
            get {
                return ((string)(this["GetFolderContentsUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("folders/subfolders?parentfolder={parentfolderpath}&filter={filter}")]
        public string GetChildFoldersFilteredUri {
            get {
                return ((string)(this["GetChildFoldersFilteredUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("folders/contents?parentfolder={parentfolderpath}&filter={filter}")]
        public string GetFolderContentsFilteredUri {
            get {
                return ((string)(this["GetFolderContentsFilteredUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("folders/files?parentfolder={parentfolderpath}&filter={filter}")]
        public string GetChildFilesFilteredUri {
            get {
                return ((string)(this["GetChildFilesFilteredUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files/parent?path={filepath}")]
        public string GetFileParentUri {
            get {
                return ((string)(this["GetFileParentUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("folders/parent?path={folderpath}")]
        public string GetFolderParentUri {
            get {
                return ((string)(this["GetFolderParentUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files/availability?path={filepath}")]
        public string IsFileAvailableUri {
            get {
                return ((string)(this["IsFileAvailableUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("folders/availability?path={folderpath}")]
        public string IsFolderAvailableUri {
            get {
                return ((string)(this["IsFolderAvailableUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files?path={filepath}")]
        public string DeleteFileUri {
            get {
                return ((string)(this["DeleteFileUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("folders?path={folderpath}")]
        public string DeleteFolderUri {
            get {
                return ((string)(this["DeleteFolderUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("folders?path={folderpath}")]
        public string CreateFolderUri {
            get {
                return ((string)(this["CreateFolderUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files/copy?source={filepath}&destination={destinationpath}")]
        public string CopyFileUri {
            get {
                return ((string)(this["CopyFileUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files/move?source={filepath}&destination={destinationpath}")]
        public string MoveFileUri {
            get {
                return ((string)(this["MoveFileUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("folders/copy?source={folderpath}&destination={destinationpath}")]
        public string CopyFolderUri {
            get {
                return ((string)(this["CopyFolderUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("folders/move?source={folderpath}&destination={destinationpath}")]
        public string MoveFolderUri {
            get {
                return ((string)(this["MoveFolderUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files/combinedpath?parentfolder={parentfolderpath}&filename={filename}")]
        public string CreateFilePathUri {
            get {
                return ((string)(this["CreateFilePathUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("folders/combinedpath?parentfolder={parentfolderpath}&foldername={foldername}")]
        public string CreateFolderPathUri {
            get {
                return ((string)(this["CreateFolderPathUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("downloads/maxblocksize")]
        public string GetMaxDownloadBlockSizeUri {
            get {
                return ((string)(this["GetMaxDownloadBlockSizeUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uploads/maxblocksize")]
        public string GetMaxUploadBlockSizeUri {
            get {
                return ((string)(this["GetMaxUploadBlockSizeUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("downloads/{transferid}/status")]
        public string GetDownloadTransferStatusUri {
            get {
                return ((string)(this["GetDownloadTransferStatusUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uploads/{transferid}/status\r\n")]
        public string GetUploadTransferStatusUri {
            get {
                return ((string)(this["GetUploadTransferStatusUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{filter}")]
        public string PatternFilter {
            get {
                return ((string)(this["PatternFilter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{filepath}")]
        public string PatternFilePath {
            get {
                return ((string)(this["PatternFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{folderpath}")]
        public string PatternFolderPath {
            get {
                return ((string)(this["PatternFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{destinationpath}")]
        public string PatternDestinationPath {
            get {
                return ((string)(this["PatternDestinationPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{filename}")]
        public string PatternFileName {
            get {
                return ((string)(this["PatternFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{parentfolderpath}")]
        public string PatternParentFolderPath {
            get {
                return ((string)(this["PatternParentFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{foldername}")]
        public string PatternFolderName {
            get {
                return ((string)(this["PatternFolderName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{transferid}")]
        public string PatternTransferId {
            get {
                return ((string)(this["PatternTransferId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{blocknumber}")]
        public string PatternBlockNumber {
            get {
                return ((string)(this["PatternBlockNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{reason}")]
        public string PatternAbortReason {
            get {
                return ((string)(this["PatternAbortReason"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{includefilehash}")]
        public string PatternIncludeFileHash {
            get {
                return ((string)(this["PatternIncludeFileHash"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{maxblocksize}")]
        public string PatternMaxBlockSize {
            get {
                return ((string)(this["PatternMaxBlockSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files/read?path={filepath}")]
        public string ReadFileContentsUri {
            get {
                return ((string)(this["ReadFileContentsUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files/downloadtoken?file={filepath}&includefilehash={includefilehash}")]
        public string GetDownloadTokenUri {
            get {
                return ((string)(this["GetDownloadTokenUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files/downloadtoken?file={filepath}&includefilehash={includefilehash}&maxblocksiz" +
            "e={maxblocksize}")]
        public string GetDownloadTokenWithMaxBlockSizeUri {
            get {
                return ((string)(this["GetDownloadTokenWithMaxBlockSizeUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("downloads/{transferid}/token")]
        public string ReloadDownloadTokenUri {
            get {
                return ((string)(this["ReloadDownloadTokenUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("downloads/{transferid}/datablock/{blocknumber}")]
        public string GetDataBlockStreamedUri {
            get {
                return ((string)(this["GetDataBlockStreamedUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("downloads/{transferid}/data")]
        public string ReadFileContentsByTokenUri {
            get {
                return ((string)(this["ReadFileContentsByTokenUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("downloads/{transferid}/complete")]
        public string CompleteDownloadTransferUri {
            get {
                return ((string)(this["CompleteDownloadTransferUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uploads/{transferid}/complete")]
        public string CompleteUploadTransferUri {
            get {
                return ((string)(this["CompleteUploadTransferUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("downloads/{transferid}/pause")]
        public string PauseDownloadTransferUri {
            get {
                return ((string)(this["PauseDownloadTransferUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uploads/{transferid}/pause")]
        public string PauseUploadTransferUri {
            get {
                return ((string)(this["PauseUploadTransferUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("downloads/{transferid}/cancel?abortreason={reason}")]
        public string CancelDownloadTransferUri {
            get {
                return ((string)(this["CancelDownloadTransferUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uploads/{transferid}/cancel?abortreason={reason}")]
        public string CancelUploadTransferUri {
            get {
                return ((string)(this["CancelUploadTransferUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("downloads/transmissioncapabilities")]
        public string GetDownloadTransmissionCapabilitiesUri {
            get {
                return ((string)(this["GetDownloadTransmissionCapabilitiesUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uploads/transmissioncapabilities")]
        public string GetUploadTransmissionCapabilitiesUri {
            get {
                return ((string)(this["GetUploadTransmissionCapabilitiesUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uploads/{transferid}/token")]
        public string ReloadUploadTokenUri {
            get {
                return ((string)(this["ReloadUploadTokenUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uploads/maxfilesize")]
        public string GetMaxFileUploadSizeUri {
            get {
                return ((string)(this["GetMaxFileUploadSizeUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uploads/{transferid}/datablock/{blocknumber}")]
        public string WriteStreamedDataBlockUri {
            get {
                return ((string)(this["WriteStreamedDataBlockUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uploads/{transferid}/complete?hash={filehash}")]
        public string CompleteUploadTransferWithVerificationUri {
            get {
                return ((string)(this["CompleteUploadTransferWithVerificationUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{filehash}")]
        public string PatternFileHash {
            get {
                return ((string)(this["PatternFileHash"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files/write?path={filepath}")]
        public string WriteFileContentsUri {
            get {
                return ((string)(this["WriteFileContentsUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("files/uploadtoken?file={filepath}&overwrite={overwrite}&length={filelength}&conte" +
            "nttype={contenttype}")]
        public string GetUploadTokenUri {
            get {
                return ((string)(this["GetUploadTokenUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{overwrite}")]
        public string PatternOverwrite {
            get {
                return ((string)(this["PatternOverwrite"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{filelength}")]
        public string PatternFileLength {
            get {
                return ((string)(this["PatternFileLength"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{contenttype}")]
        public string PatternContentType {
            get {
                return ((string)(this["PatternContentType"]));
            }
        }
    }
}
